#name: EF Update
#
#on:
#  push:
#    branches: [ main ]
#    
#    
#jobs:
#  apply-migrations:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up .NET
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: '7.0'
#          
#      - name: Install EF Core CLI
#        run: dotnet tool install --global dotnet-ef --version 7.0.14
#
#      - name: Apply EF Migrations
#        run: |
#          cd cloud-notes-webapp
#          dotnet ef database update --project cloud-notes-webapp.csproj
#        env:
#          ConnectionString: ${{ secrets.CONNECTION_STRING }}